const cppc = require('./cppc')

test('error: empty program', () => {
    expect(() => cppc('')).toThrow()
})

test('error: no 4-tuples', () => {
    expect(() => cppc('.')).toThrow()
    expect(() => cppc(':')).toThrow()
    expect(() => cppc('..')).toThrow()
    expect(() => cppc('::')).toThrow()
    expect(() => cppc('...')).toThrow()
    expect(() => cppc(':::')).toThrow()
    expect(() => cppc('.... .')).toThrow()
    expect(() => cppc(':::: :')).toThrow()
    expect(() => cppc('.... ..')).toThrow()
    expect(() => cppc(':::: ::')).toThrow()
    expect(() => cppc('.... ...')).toThrow()
    expect(() => cppc(':::: :::')).toThrow()
})

test('error: ill-formed loops', () => {
    expect(() => cppc('...:')).toThrow()
    expect(() => cppc(':...')).toThrow()
    expect(() => cppc(':..: :...')).toThrow()
    expect(() => cppc(':... ...: :...')).toThrow()
    expect(() => cppc(':... ...: ...:')).toThrow()
})

test('max steps: infinite loops', () => {
    expect(() => cppc(':..:')).toThrow()
    expect(() => cppc('::::')).toThrow()
    expect(() => cppc(':... ...:')).toThrow()
    expect(() => cppc(':... .... ...:')).toThrow()
})

test('increment', () => {
    expect(cppc('.:..')).toStrictEqual([1, 0, 0, 0])
    expect(cppc('.:.. .:..')).toStrictEqual([1, 1, 0, 0])
    expect(cppc('.:.. .:.. .:..')).toStrictEqual([1, 1, 1, 0])
    expect(cppc('.:.. .:.. .:..')).toStrictEqual([1, 1, 1, 0])
    expect(cppc('.:.. .:.. .:.. .:..')).toStrictEqual([1, 1, 1, 1])
    expect(cppc('.:.. .:.. .:.. .:.. .:..')).toStrictEqual([2, 1, 1, 1])
    expect(cppc('.:.. .:.. .:.. .:.. .:.. .:..')).toStrictEqual([2, 2, 1, 1])
    expect(cppc('.:.. .:.. .:.. .:.. .:.. .:.. .:..')).toStrictEqual([2, 2, 2, 1])
    expect(cppc('.:.. .:.. .:.. .:.. .:.. .:.. .:.. .:..')).toStrictEqual([2, 2, 2, 2])
})

test('decrement', () => {
    expect(cppc('..:.')).toStrictEqual([0, 0, 0, 0])
    expect(cppc('..:. ..:.')).toStrictEqual([0, 0, 0, 0])
    expect(cppc('.:.. .:.. ..:.')).toStrictEqual([1, 1, 0, 0])
    expect(cppc('.:.. .... ..:.')).toStrictEqual([1, 0, 0, 0])
    expect(cppc('.:.. .:.. ..:.')).toStrictEqual([1, 1, 0, 0])
    expect(cppc('.:.. .:.. .:.. .:.. .:.. ..:.')).toStrictEqual([2, 0, 1, 1])
    expect(cppc('.:.. .:.. .:.. .:.. .:.. ..:. ..:.')).toStrictEqual([2, 0, 0, 1])
    expect(cppc('.:.. .:.. .:.. .:.. .:.. ..:. ..:. ..:.')).toStrictEqual([2, 0, 0, 0])
    expect(cppc('.:.. .:.. .:.. .:.. .:.. ..:. ..:. ..:. ..:.')).toStrictEqual([1, 0, 0, 0])
})

test('loop', () => {
    expect(cppc(':..:', 1)).toStrictEqual([1, 0, 0, 0])
    expect(cppc('::.:', 1)).toStrictEqual([1, 0, 0, 0])
    expect(cppc('::.:')).toStrictEqual([1, 0, 0, 0])
    expect(cppc('::.:')).toStrictEqual([1, 0, 0, 0])
    expect(cppc('::.. ...:')).toStrictEqual([1, 0, 0, 0])
    expect(cppc('::.. .:.:')).toStrictEqual([1, 1, 0, 0])
    expect(cppc('::.. .:.. ...:')).toStrictEqual([1, 1, 0, 0])
    expect(cppc('::.: .:..')).toStrictEqual([1, 1, 0, 0])
    expect(cppc('::.. .:.. .:.. ...:')).toStrictEqual([1, 1, 1, 0])
    expect(cppc('::.. .:.. .:.. .:.:')).toStrictEqual([1, 1, 1, 1])
    expect(cppc(':... .... .... .... .:.:')).toStrictEqual([1, 0, 0, 0])
    expect(cppc(':... .:.. .... .... .:.:')).toStrictEqual([1, 1, 0, 0])
})

test('nested loop', () => {
    expect(cppc('::.. ::.. ...: .... ...:')).toStrictEqual([1, 1, 0, 0])
    expect(cppc(':... ::.. ...: .... .:.:')).toStrictEqual([1, 1, 0, 0])
    expect(cppc('::.. ::.. ...: .... .:.:')).toStrictEqual([2, 1, 0, 0])
    expect(cppc('::.. ::.. ::.. ...: ...: ...:')).toStrictEqual([1, 1, 1, 0])
    expect(cppc('::.. ::.. ...: ::.. ...: ...:')).toStrictEqual([1, 1, 0, 1])
    expect(cppc('::.. .... .... .... :... .:.. ...: ...:')).toStrictEqual([1, 0, 0, 0])
    expect(cppc(':... .... .... .... ::.. .:.. ...: ...:')).toStrictEqual([1, 1, 0, 0])
    expect(cppc(':... .... .... .... :... .... .... .... .:.: ...:')).toStrictEqual([1, 0, 0, 0])
    expect(cppc(':... .... .... .... :... .... .... .... .:.: .:.:')).toStrictEqual([1, 1, 0, 0])
    expect(cppc(':... .... .... .... :... .... .... .... .:.: .... .... .... .:.:')).toStrictEqual([2, 0, 0, 0])
})

test('clear', () => {
    const clear = `
        .... .... :... ....
        :... .... .:.. ....
        .:.: .... .... ....
        ..:: .... ..:. ....
    `
    expect(cppc(clear)).toStrictEqual([0, 0, 0, 0])
    expect(cppc(clear, 1)).toStrictEqual([0, 0, 0, 0])
    expect(cppc(clear, 42)).toStrictEqual([0, 0, 0, 0])
})

test('move', () => {
    const move = `
        .... .... :... ....
        .... :... .:.. ....
        .... .:.: .... ....
        .:.. ..:. ...: ....
        ..:. ..:. ..:. ....
    `
    expect(cppc(move)).toStrictEqual([0, 0, 0, 0])
    expect(cppc(move, 1, 0)).toStrictEqual([1, 0, 0, 0])
    expect(cppc(move, 0, 1)).toStrictEqual([1, 0, 0, 0])
    expect(cppc(move, 42, 0)).toStrictEqual([42, 0, 0, 0])
    expect(cppc(move, 0, 42)).toStrictEqual([42, 0, 0, 0])
    expect(cppc(move, 42, 123)).toStrictEqual([165, 0, 0, 0])
})

test('copy', () => {
    const copy = `
        .... .... :... ....
        :... .... .:.. ....
        .:.: .... .... ....
        ..:. .:.. .... .:.:
        .... ..:. ..:. ..:.
        .... .... :... :...
        .... .... .:.. .:.:
        .... .... .... ..:.
        .:.: .... .... ....
        ..:. .... ..:. ....
    `
    expect(cppc(copy)).toStrictEqual([0, 0, 0, 0])
    expect(cppc(copy, 1)).toStrictEqual([1, 1, 0, 0])
    expect(cppc(copy, 42)).toStrictEqual([42, 42, 0, 0])
    expect(cppc(copy, 42, 42)).toStrictEqual([42, 84, 0, 0])
})

test('switch', () => {
    const switc = `
        .... .... :... ....
        ::.. .... .:.: .:..
        ..:: .... ..:. ..:.
        .... .... :... ....
        .... ::.. .:.: ....
        .:.. ..:: ..:. ....
        ..:. .... :... ::..
        .... .... .:.: ..:.
        .... .:.: ..:. ....
        .... ..:. .... ....
    `
    expect(cppc(switc)).toStrictEqual([0, 0, 0, 0])
    expect(cppc(switc, 1, 0)).toStrictEqual([0, 1, 0, 0])
    expect(cppc(switc, 0, 1)).toStrictEqual([1, 0, 0, 0])
    expect(cppc(switc, 42, 0)).toStrictEqual([0, 42, 0, 0])
    expect(cppc(switc, 0, 42)).toStrictEqual([42, 0, 0, 0])
})

test('fibonacci', () => {
    const fibonacci = `
        .... .:.. :... ....
        .... .... :... ....
        ::.. .... .:.: .:..
        ..:: .... ..:. ..:.
        .... .... :... ....
        .... ::.. .:.: ....
        .:.. ..:: ..:. ....
        ..:. .... :... ::..
        .... .... .:.: ..:.
        .... .:.: ..:. ....
        .... ..:. :... ....
        ::.. .... .:.: .:..
        ..:. .:.: ..:. ..:.
        .... ..:. :... ::..
        .... .... .:.: ..:.
        .:.: .... ..:. ....
        ..:: .... .... ....
    `
    const results = [1] // start with 1 not have to deal with 1 1 subsequence
    let last = 0
    const onStepFinished = regs => {
        if (regs[0] < last) {   // another item in the sequence is ready
            if (regs[0] > results[results.length - 1])
                results.push(regs[0])
        }
        last = regs[0]        
    }
    cppc(fibonacci, 0, 0, 0, 0, 1000, onStepFinished)

    console.log(results)
    expect(results.slice(0, 6)).toStrictEqual([1, 2, 3, 5, 8, 13])
})

test('Hello World', () => {
    const hello = `
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....

        .... .... :... ....
        :... .... .:.. ....
        .:.: .... .... ....
        ..:: .... ..:. ....

        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....

        .... .... :... ....
        :... .... .:.. ....
        .:.: .... .... ....
        ..:: .... ..:. ....

        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....

        .... .... :... ....
        :... .... .:.. ....
        .:.: .... .... ....
        ..:: .... ..:. ....

        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....

        .... .... :... ....
        :... .... .:.. ....
        .:.: .... .... ....
        ..:: .... ..:. .... 

        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....

        .... .... :... ....
        :... .... .:.. ....
        .:.: .... .... ....
        ..:: .... ..:. ....  

        .:.. .... .... ....

        .... .... :... ....
        :... .... .:.. ....
        .:.: .... .... ....
        ..:: .... ..:. ....  

        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....

        .... .... :... ....
        :... .... .:.. ....
        .:.: .... .... ....
        ..:: .... ..:. .... 

        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....

        .... .... :... ....
        :... .... .:.. ....
        .:.: .... .... ....
        ..:: .... ..:. .... 

        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....

        .... .... :... ....
        :... .... .:.. ....
        .:.: .... .... ....
        ..:: .... ..:. .... 

        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....
        .:.. .... .... ....

        .... .... :... ....
        :... .... .:.. ....
        .:.: .... .... ....
        ..:: .... ..:. .... 

        .:.. .... .... ....
        .:.. .... .... ....

        .... .... :... ....
        :... .... .:.. ....
        .:.: .... .... ....
        ..:: .... ..:. .... 
    `
    const result = []
    cppc(hello, 0, 0, 0, 0, null, collectChanges(result))

    const alphabet = []
    alphabet[1] = ' '
    alphabet[2] = 'd'
    alphabet[3] = 'e'
    alphabet[4] = 'H'
    alphabet[5] = 'l'
    alphabet[6] = 'o'
    alphabet[7] = 'r'
    alphabet[8] = 'W'

    let msg = ''
    for (let i = 0; i < result.length; i += 2) {
        msg += alphabet[result[i]]
    }

    expect(msg).toStrictEqual('Hello World')

    function collectChanges(result) {
      let last = 0, zero = true
      return  r => {
        if (r[0] < last && zero) {  // value change
          result.push(last)
          zero = false
        }
        last = r[0]
        if (last === 0) zero = true
      }
    }
})

test('while r(x)', () => {   /* r == A */
    const whil = `
        :... .... .:.. ....
        .:.: .... .... ....
        ..:. .... :... ....
        .:.. .... .... ....

        ..:. .:.. .... ....  x = A- B+

        :... .... .:.. ....
        .:.: .... .... ....
        ..:: .... ..:. ....
    `
    expect(cppc(whil)).toStrictEqual([0, 0, 0, 0])
    expect(cppc(whil, 1)).toStrictEqual([0, 1, 0, 0])
    expect(cppc(whil, 3)).toStrictEqual([0, 3, 0, 0])
    expect(cppc(whil, 42)).toStrictEqual([0, 42, 0, 0])
})

test('if-else r{x|y}', () => {   /* r == A */
    const ifelse = `
        :... .... .... ....

        .... .:.. .... ....  x = B+

        .:.. .... .:.: ....
        ..:. .... :... ....
        .:.. .... .... ....

        .... .... .... .:..  y = D+

        .... .... .:.: ....
        .... .... ..:. ....
    `
    expect(cppc(ifelse, 0)).toStrictEqual([0, 1, 0, 0])
    expect(cppc(ifelse, 1)).toStrictEqual([1, 0, 0, 1])
    expect(cppc(ifelse, 42)).toStrictEqual([42, 0, 0, 1])
})

test('program machine', () => {
    const pmachine = `
        .... .... .... .:..     D+

        .... .... .... :...     while D > 0
        .... .... .:.. .:.:
        .... .... .... ..:.
        .... .... :... .:..

        .... .... :... ....     1 match?
        .... .... .... ..:.     D-
        .... .... .... :...     

        :... .... .... ....     A{ D+ D+ D+ | D+ D+ }
        
        .... .... .... .:..     D+ D+ D+
        .... .... .... .:..
        .... .... .... .:..

        .:.. .... .:.: ....
        ..:. .... :... ....
        .:.. .... .... ....
        
        .... .... .... .:..     D+ D+
        .... .... .... .:..

        .... .... .:.: ....     end if-else
        .... .... ..:. ....     

        .... .... .:.. ....     C+ C+ C+ D+] D- C[ D+ D+       C+] ] C-
        .... .... .:.. ....
        .... .... .:.. ....
        .... .... .... .:.:
        .... .... .... ..:.
        .... .... :... .:..     
        .... .... .... .:..     D+
        .... .... .:.: ...:
        .... .... ..:. ....

        .... .... :... ....     2 match?
        .... .... .... ..:.     D-
        .... .... .... ..:.     D-
        .... .... .... :...     

        ..:. .... .... .:..     A- D+ 

        .... .... .:.. ....     C+ C+ D+] D- C[ D+ D+       C+] ] C-
        .... .... .:.. ....
        .... .... .... .:.:
        .... .... .... ..:.
        .... .... :... .:..     
        .... .... .... .:..     D+
        .... .... .... .:..     D+
        .... .... .:.: ...:
        .... .... ..:. ....

        .... .... :... ....     3 match?
        .... .... .... ..:.     D-
        .... .... .... ..:.     D-
        .... .... .... ..:.     D-
        .... .... .... :...     

        .:.. .... .... ....     A+ (D remains 0)

        .... .... .:.. ....     C+ C+ D+] D- C[ D+ D+       C+] ] C-
        .... .... .:.. ....
        .... .... .... .:.:
        .... .... .... ..:.
        .... .... :... .:..     
        .... .... .... .:..     D+
        .... .... .... .:..     D+
        .... .... .... .:..     D+
        .... .... .:.: ...:
        .... .... ..:. ....
        
        .... .... ..:. ....     C-  reset search

        .... .... .... :...     end while
        .... .... .:.. .:.:
        .... .... .... ..::
        .... .... ..:. ....

    `
    expect(cppc(pmachine, 0)).toStrictEqual([1, 0, 0, 0])
    expect(cppc(pmachine, 1)).toStrictEqual([1, 0, 0, 0])
    expect(cppc(pmachine, 3)).toStrictEqual([1, 0, 0, 0])
    expect(cppc(pmachine, 42)).toStrictEqual([1, 0, 0, 0])
})